### PR TITLE
add schex vignette only

### PR DESCRIPTION
**Pull request by SaskiaFreytag**
I hope this solves the other pull request.

### CODE REVIEW

**Comment by mojaveazure** [comment]
Hi Saskia,

This looks great! One concern though, when testing the vignette locally, I get the following error:

```R
> label_df <- make_hexbin_label(pbmc, col="RNA_snn_res.0.5")
Error in cluster::pam(x, 1) : 
  Number of clusters 'k' must be in {1,2, .., n-1}; hence n >= 2
```

Do you know what's going on here?

**Comment by SaskiaFreytag** [comment]
I cannot recreate that error. Can you send me your session information?

**Comment by mojaveazure** [comment]
```R
> sessionInfo()
R version 3.5.3 (2019-03-11)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.6 LTS

Matrix products: default
BLAS: /usr/lib/openblas-base/libblas.so.3
LAPACK: /usr/lib/libopenblasp-r0.2.18.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] parallel  stats4    stats     graphics  grDevices utils     datasets 
[8] methods   base     

other attached packages:
 [1] ggrepel_0.8.1               schex_0.1.0                
 [3] dplyr_0.8.3                 ggplot2_3.2.0              
 [5] SingleCellExperiment_1.4.1  SummarizedExperiment_1.12.0
 [7] DelayedArray_0.8.0          BiocParallel_1.16.6        
 [9] matrixStats_0.54.0          Biobase_2.42.0             
[11] GenomicRanges_1.34.0        GenomeInfoDb_1.18.2        
[13] IRanges_2.16.0              S4Vectors_0.20.1           
[15] BiocGenerics_0.28.0         pbmc3k.SeuratData_3.0.0    
[17] cbmc.SeuratData_3.0.0       SeuratData_0.1.0.9000      
[19] Seurat_3.0.3.9019          

loaded via a namespace (and not attached):
 [1] Rtsne_0.15             colorspace_1.4-1       ggridges_0.5.1        
 [4] XVector_0.22.0         rstudioapi_0.10        hexbin_1.27.3         
 [7] listenv_0.7.0          npsurv_0.4-0           codetools_0.2-16      
[10] splines_3.5.3          R.methodsS3_1.7.1      lsei_1.2-0            
[13] knitr_1.23             jsonlite_1.6           ica_1.0-2             
[16] cluster_2.0.9          png_0.1-7              R.oo_1.22.0           
[19] sctransform_0.2.0      compiler_3.5.3         httr_1.4.0            
[22] assertthat_0.2.1       Matrix_1.2-17          lazyeval_0.2.2        
[25] cli_1.1.0              htmltools_0.3.6        tools_3.5.3           
[28] rsvd_1.0.2             igraph_1.2.4.1         gtable_0.3.0          
[31] glue_1.3.1             GenomeInfoDbData_1.2.0 RANN_2.6.1            
[34] reshape2_1.4.3         rappdirs_0.3.1         Rcpp_1.0.2            
[37] gdata_2.18.0           ape_5.3                nlme_3.1-140          
[40] gbRd_0.4-11            lmtest_0.9-37          xfun_0.7              
[43] stringr_1.4.0          globals_0.12.4         irlba_2.3.3           
[46] gtools_3.8.1           future_1.14.0          MASS_7.3-51.4         
[49] zlibbioc_1.28.0        zoo_1.8-6              scales_1.0.0          
[52] RColorBrewer_1.1-2     yaml_2.2.0             reticulate_1.13       
[55] pbapply_1.4-1          gridExtra_2.3          stringi_1.4.3         
[58] caTools_1.17.1.2       bibtex_0.4.2           Rdpack_0.11-0         
[61] SDMTools_1.1-221.1     rlang_0.4.0            pkgconfig_2.0.2       
[64] bitops_1.0-6           lattice_0.20-38        ROCR_1.0-7            
[67] purrr_0.3.2            labeling_0.3           htmlwidgets_1.3       
[70] cowplot_1.0.0          tidyselect_0.2.5       RcppAnnoy_0.0.12      
[73] plyr_1.8.4             magrittr_1.5           R6_2.4.0              
[76] gplots_3.0.1.1         pillar_1.4.2           withr_2.1.2           
[79] fitdistrplus_1.0-14    survival_2.44-1.1      RCurl_1.95-4.12       
[82] tibble_2.1.3           future.apply_1.3.0     tsne_0.1-3            
[85] crayon_1.3.4           KernSmooth_2.23-15     plotly_4.9.0          
[88] grid_3.5.3             data.table_1.12.2      metap_1.1             
[91] digest_0.6.20          tidyr_0.8.3            R.utils_2.9.0         
[94] munsell_0.5.0          viridisLite_0.3.0 
```

**Comment by mojaveazure** [comment]
Hi Saskia,

I've built a Docker image where the error reproduces. The Dockerfile spec is as follows

```dockerfile
#   Docker image for the latest build of Seurat
FROM ubuntu:bionic

#   Set up the system for Seurat
#   Don't ask for user input
ENV DEBIAN_FRONTEND=noninteractive
ENV DEBCONF_NONINTERACTIVE_SEEN=true
#   Configure tzdata (ish)
RUN echo 'tzdata tzdata/Areas select US' | debconf-set-selections
RUN echo 'tzdata tzdata/Zones/US select New York' | debconf-set-selections
#   Add CRAN PPA
RUN apt-get update
RUN apt-get install -y ca-certificates gnupg2
RUN echo "deb https://cloud.r-project.org/bin/linux/ubuntu bionic-cran35/" | tee --append /etc/apt/sources.list
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
#   Install R
RUN apt-get update
RUN apt-get install -y r-base-dev

#   Install system Seurat dependencies
RUN apt-get install -y libhdf5-dev libcurl4-openssl-dev libssl-dev libxml2-dev

#   Install Seurat
RUN R --slave --no-restore --no-save -e "install.packages('devtools', repos = 'https://cloud.r-project.org')"
RUN R --slave --no-restore --no-save -e "install.packages('Seurat', repos='https://cloud.r-project.org')"
RUN R --slave --no-restore --no-save -e "install.packages('BiocManager', repos='https://cloud.r-project.org')"
RUN R --slave --no-restore --no-save -e "BiocManager::install(c('scater', 'SingleCellExperiment'))"
RUN R --slave --no-restore --no-save -e "devtools::install_github('satijalab/seurat-data')"
RUN R --slave --no-restore --no-save -e "devtools::install_github('SaskiaFreytag/seurat-wrappers')"
RUN R --slave --no-restore --no-save -e "devtools::install_github('SaskiaFreytag/schex')"
RUN R --slave --no-restore --no-save -e "install.packages('knitr', repos='https://cloud.r-project.org')"

#   Install Python/UMAP
RUN apt-get install -y python-pip
RUN pip install umap-learn

#   Get schex fork of SeuratWrappers
RUN apt-get install -y git
RUN git clone https://github.com/SaskiaFreytag/seurat-wrappers
WORKDIR /seurat-wrappers/docs
RUN R --slave --no-restore --no-save -e "knitr::purl('schex.Rmd')"

ENTRYPOINT [ "/usr/bin/env", "R" ]
```
You can save this as a file called Dockerfile and build it with

```bash
sudo docker build . -t schex
```

Once built, you can run to the point of failure with

```bash
sudo docker run -it --rm schex --no-restore --no-save -e "source('schex.R', echo=TRUE, verbose=TRUE)"
```

If you want to jump into an interactive session to get session information and other details, run

```bash
sudo docker run -it --rm schex
```

**Comment by SaskiaFreytag** [comment]
Hey,

Thanks for building a dockerfile. However, I cannot run it as I have no sudo access on our ubuntu servers. I have tried running it on my Mac, but that result in errors :(.

I have tried to address the bug though in a new version of schex. Since I cannot recreate it I have no ways of testing whether I fixed the problem. So would you mind checking? (I am sorry that this is such a drag).

**Comment by mojaveazure** [comment]
Hi Saskia,

Unfortunately, no, it hasn't solved the bug. What was the error with the Docker image on your Mac (in theory, there shouldn't be; that's the point of Docker so I'm genuinely curious)?

**Comment by SaskiaFreytag** [comment]
This is the error.
`Error in loadNamespace(name) : there is no package called 'devtools'
Calls: :: ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted`

**Comment by mojaveazure** [comment]
Hi Saskia,

That's a weird error; I'm not sure why that would come up.

Here's a revised Dockerfile that doesn't use devtools, but still reproduces the error. In addition, we're working on getting CI set up as another test environment.

```Dockerfile
FROM rstudio/r-base:3.5-bionic

#   Install Git and other system dependencies
RUN apt-get update
RUN apt-get install -y git libhdf5-dev libcurl4-openssl-dev libssl-dev libxml2-dev libpng-dev

#   Set R options
RUN RHOME=$(R --slave --no-restore --no-save -e "cat(Sys.getenv('R_HOME'))") && \
    mkdir -vp ${RHOME}/library && \
    echo "options(repos = 'https://cloud.r-project.org')" > ${RHOME}/etc/Rprofile.site && \
    echo ".libPaths(new = '${RHOME}/library')" >> ${RHOME}/etc/Rprofile.site

#   Install Seurat and other packages from CRAN/Bioconductor
RUN R --slave --no-restore --no-save -e "install.packages('knitr')"
RUN R --slave --no-restore --no-save -e "install.packages('Seurat')"
RUN R --slave --no-restore --no-save -e "install.packages('BiocManager')"
RUN R --slave --no-restore --no-save -e "BiocManager::install(c('scater', 'SingleCellExperiment'))"

#   Install UMAP
RUN apt-get install -y python3-dev python3-pip
RUN pip3 install umap-learn

#   Install packages from GitHub
RUN R --slave --no-restore --no-save -e "install.packages(c('cli', 'crayon'))"
RUN git clone https://github.com/satijalab/seurat-data
RUN R CMD build --no-build-vignettes seurat-data
RUN R CMD INSTALL $(find . -maxdepth 1 -name "SeuratData*.tar.gz")

RUN R --slave --no-restore --no-save -e "install.packages(c('cluster', 'dplyr', 'rmarkdown', 'here'))"
RUN git clone https://github.com/SaskiaFreytag/schex
RUN R CMD build --no-build-vignettes schex
RUN R CMD INSTALL $(find . -maxdepth 1 -name "schex*.tar.gz")

RUN R --slave --no-restore --no-save -e "install.packages('remotes')"
RUN git clone https://github.com/SaskiaFreytag/seurat-wrappers
RUN R CMD build --no-build-vignettes seurat-wrappers
RUN R CMD INSTALL $(find . -maxdepth 1 -name "SeuratWrappers*.tar.gz")

#   Get an Rscript version of the schex vignette
WORKDIR /seurat-wrappers/docs
RUN R --slave --no-restore --no-save -e "knitr::purl('schex.Rmd')"

ENTRYPOINT [ "/usr/bin/env", "R" ]
```

**Comment by andrewwbutler** [comment]
Ok, I think we have the CI environment mostly set up now. Sorry for all the hassle @SaskiaFreytag. It looks like it builds successfully (not sure what was happening with the Docker stuff) but the output from `plot_hexbin_meta` looks a bit weird. You can download the build artifacts (the Vignettes zip file) [here]( https://dev.azure.com/seuratpackage/seurat-wrappers/_build/results?buildId=64&view=results). Any ideas why it might be different from what you originally submitted?

**Comment by SaskiaFreytag** [comment]
Thank you so much fo looking into this so thoroughly. I am glad it is at least not running into errors any longer. I have seen the weird artefact before, when there are few observations.  However, I can never reproducibly recreate it. I have changed the number of nbins, which normally solves it. So maybe it will work now for you.

**Comment by andrewwbutler** [comment]
Looks good now! I edited the vignette slightly to compress the preprocessing/clustering steps so that people could focus on the schex features (we're working on hosting more processed versions of Seurat objects via SeuratData for situations like this but that's still a bit of a WIP). If you're ok with the changes, we'll get this merged in and added to the website [list](https://satijalab.org/seurat/vignettes.html#seurat-wrappers).

**Comment by SaskiaFreytag** [comment]
Happy for the changes! Sorry it took me so long to reply!

**Comment by andrewwbutler** [comment]
Great! Thanks again for contributing!

**Pull request merged**
