### PR TITLE
Updates to RunBanksy

### PR DESCRIPTION
**Pull request by jleechung**
This PR implements:
- a minor fix to feature handling.
- computation of the scaled BANKSY matrix (using `Seurat:::FastRowScale`).
- computation of the azimuthal Gabor filter.

### CODE REVIEW

**Comment by jleechung** [comment]
Hi @mojaveazure ,

We are trying to push some updates to `RunBanksy` but the GitHub action checks are failing at the `SeuratWrappers` installation stage. Do you know how to resolve the errors? Let us know if there's anything we can do on our end. 

Thank you!

**Comment by jleechung** [comment]
Hi @dcollins15, we're trying to push some changes to BANKSY so users can directly install from this repo instead of our fork - but checks are failing at installation - do you know why this is the case? thank you!

**Review by vipulsinghal02 — APPROVED** [review]
Look good!

**Comment by dcollins15** [comment]
Apologies for the long delay and thanks for the updates - these changes LGTM! 🥳 

Updating the pre-merge check is slowly creeping up my ToDo list but you can ignore the failures for now 🙃 

Before this is ready to be merged there are just a couple of small house-keeping things to take care of:

1. Please rebase onto `master` 
2. Please update the package's DESCRIPTION to increment the version to `0.3.5` and also update the date

**Review by dcollins15 — APPROVED** [review]
Wicked! Thanks @jleechung, I'll merge this in shortly 🙌

**Comment by jleechung** [comment]
Thank you!

**Pull request merged**
